base_dir: /home/feesh/PycharmProjects/FaceEmbedder
train:
  batch_size: 8
  people_num: 7
  img_num: 3
data:
  width: 100
  height: 100
  data_path: cropped_images
  train_num: 8000
  test_num: 1000

